const courses = [
    {
        id: 1,
        name: 'HTML, CSS PRO',
        price: 50,
        level: 'Beginner',
        skill: 'listening',
    },
    {
        id: 2,
        name: 'JavaScript Pro',
        price: 55,
        level: 'All Levels',
        skill: 'speaking',
    },
    {
        id: 3,
        name: 'React JS Pro',
        price: 60,
        level: 'All Levels',
        skill: 'listening',
    },
    {
        id: 4,
        name: 'Kiến thức nhập môn IT',
        price: 10,
        level: 'Beginner',
        skill: 'writing',
    },
    {
        id: 5,
        name: 'Lập trình C++ cơ bản, nâng cao',
        price: 70,
        level: 'All Levels',
        skill: 'writing',
    },
    {
        id: 6,
        name: 'HTML, CSS từ Zero đến Hero',
        price: 40,
        level: 'All Levels',
        skill: 'reading',
    },
    {
        id: 7,
        name: 'Responsive với Grid System',
        price: 20,
        level: 'All Levels',
        skill: 'listening',
    },
    {
        id: 8,
        name: 'Lập trình JavaScript cơ bản',
        price: 50,
        level: 'Immediate',
        skill: 'writing',
    },
    {
        id: 9,
        name: 'Lập trình JavaScript nâng cao',
        price: 70,
        level: 'Advance',
        skill: 'speaking',
    },
    {
        id: 10,
        name: 'Làm việc với Terminal & Ubuntu',
        price: 10,
        level: 'All Levels',
        skill: 'reading',
    },
    {
        id: 11,
        name: 'Xây dựng Website với ReactJS',
        price: 100,
        level: 'All Levels',
        skill: 'writing',
    },
    {
        id: 12,
        name: 'Node & ExpressJS',
        price: 90,
        level: 'All Levels',
        skill: 'speaking',
    },
    {
        id: 13,
        name: 'PHP',
        price: 50,
        level: 'All Levels',
        skill: 'listening',
    },
    {
        id: 14,
        name: 'Java',
        price: 60,
        level: 'All Levels',
        skill: 'listening',
    },
    {
        id: 15,
        name: 'Ruby',
        price: 65,
        level: 'All Levels',
        skill: 'listening',
    },
    {
        id: 16,
        name: 'WordPress',
        price: 20,
        level: 'All Levels',
        skill: 'listening',
    },
    {
        id: 17,
        name: 'Vue JS',
        price: 100,
        level: 'All Levels',
        skill: 'listening',
    },
];

export default courses;
